# Generated by Django 5.0.6 on 2025-05-12 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trip_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Запрос на присоединение'), ('accept', 'Запрос принят'), ('decline', 'Запрос отклонен'), ('success', 'Успешное действие'), ('warning', 'Предупреждение'), ('info', 'Информационное сообщение')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.trip'),
        ),
    ]
