# Generated by Django 5.0.6 on 2025-05-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Запрос на присоединение'), ('accept', 'Запрос принят'), ('decline', 'Запрос отклонен'), ('success', 'Успешное действие'), ('warning', 'Предупреждение'), ('info', 'Информационное сообщение'), ('start', 'Поездка началась'), ('end', 'Поездка завершена'), ('removed', 'Удаление из поездки')], default='info', max_length=20),
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('is_departure', models.BooleanField(default=False)),
                ('is_destination', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='main.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
