# Generated by Django 5.0.6 on 2025-05-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trip_route_distance_trip_route_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_polyline',
        ),
    ]
