# Generated by Django 5.0.6 on 2025-05-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_trip_route_polyline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_duration',
        ),
    ]
